version: '3.1'

services:
  zookeeper:
    image: zookeeper:3.5.5
    ports:
      - "2181:2181"
    restart: always
    volumes:
      - ./zookeeper/data:/data

  zoonavigatorUi:
    image: elkozmon/zoonavigator-web:0.6.2
    ports:
      - "8000:8000"
    environment:
      WEB_HTTP_PORT: 8000
      API_HOST: "zoonavigatorApi"
      API_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: "zookeeper:2181"
    depends_on:
      - zoonavigatorApi
    restart: always

  zoonavigatorApi:
      image: elkozmon/zoonavigator-api:0.6.2
      environment:
        API_HTTP_PORT: 9000
      restart: always

